# -*- coding: utf-8 -*-
"""Projeto_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSTGLph7X1A-KCYbiMiYd-D8ITpNJ_HQ
"""

nova_operacao = 1;

while nova_operacao == 1:

				primeiro_numero = int(input('Digite o primeiro número da operação: '));

				segundo_numero = int(input('Digite o segundo numero da operação: '));

				operacao = input('Qual operação deseja realizar? +, -, *, /: ');

				while operacao != '+' and operacao != '-' and operacao != '*' and operacao != '/':

								print("Operação inválida, tente novamente!");

				if operacao == '+':

								soma = primeiro_numero + segundo_numero;

								print('O valor da soma é: ', soma);

				elif operacao == '-':

								subtracao = primeiro_numero - segundo_numero;

								print('O valor da subtração é: ', subtracao);

				elif operacao == '*':

								multiplicacao = primeiro_numero * segundo_numero;

								print('O valor da multiplicação é: ', multiplicacao);

				else:

							divisao = primeiro_numero / segundo_numero;

							print('O valor da divisão  é: ', divisao);

				continuar = input('Digite 1 para realizar uma nova operação:')

				if continuar != '1':
					nova_operacao = 0; print('Operação encerrada!');